Add support for gradle 7.1.1
sedovalx/gradle-aspectj-binary pull request #11
Opened 2021-08-05 12:02 UTC by vincenzocorso

According to #10 this plugin actualy doesn't support gradle 7.

This is related to some annotations, introduced in Gradle 7, which need to be added to `AjcTask.kt`.
This pull should solve this problem.

I've tried running examples and it seems to work.

2021-08-05 12:12 UTC, sedovalx requested changes

2021-08-05 12:12 UTC, sedovalx commented on plugin/src/main/kotlin/com/github/sedovalx/gradle/aspectj/AjcTask.kt
> +    @Optional @InputDirectory
This probably should be `@ OutputDirectory`

2021-08-05 13:34 UTC, vincenzocorso commented
You are right. 

I tried, but if I put @OutputDirectory instead of @InputDirectory, it gives an error in the examples:
```
> Task :examples:aspects:weaveClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:aspects:weaveClasses'.
> Input property 'sourceSets' with value '[source set 'main']' cannot be serialized.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
3 actionable tasks: 3 executed
```
The property `sourceSets` is of type `Set<SourceSet>`, which cannot be serialized (according to [this](https://stackoverflow.com/questions/33275970/gradle-unable-to-store-task-input-properties-property-myinput-with-value-n)) because `SourceSet` implementation doesn't implement `Serializable`.

Maybe we can convert it to `Set<String>` or something else?

2021-08-05 13:52 UTC, sedovalx commented
Let's change the type of the `AjcTask.sourceSets` property -> `Set<String>` as you suggested. The conversion can be done in https://github.com/sedovalx/gradle-aspectj-binary/blob/955fe2adc0fb10c4d55a84e7ce16b506838e65d5/plugin/src/main/kotlin/com/github/sedovalx/gradle/aspectj/AspectJBinaryWeavingPlugin.kt#L68 to preserve the API of `WeaveClassesExtension`. 

p.s.: so strange that adding `@OutputDirectory` exposes a problem with inputs serialization...

2021-08-05 15:47 UTC, vincenzocorso commented
I just saw that the input property is `ajcSourceSets` and not` sourceSets`. The sourceSets property is used internally:

https://github.com/sedovalx/gradle-aspectj-binary/blob/955fe2adc0fb10c4d55a84e7ce16b506838e65d5/plugin/src/main/kotlin/com/github/sedovalx/gradle/aspectj/AjcTask.kt#L34-L63

I put @Internal on `sourceSets` and now it doesn't give me any warning. It should be correct right?

2021-08-05 15:55 UTC, sedovalx commented
Unfortunately not. Accordingly to [the documentation](https://docs.gradle.org/current/userguide/more_about_tasks.html) internal task properties are properties which values don't affect the task output. In our case, source sets do affect the output obviously. So it should be marked as `@Input`. I still think that `AjcTask.sourceSets` property type should be changed to `Set<String>` as you suggested. 
I will try to find time today to check out this PR and do the required changes, you will need to check that this will work for your case then.

2021-08-06 07:23 UTC, closed without merging

2021-08-06 07:24 UTC, sedovalx commented
@vincenzocorso am I right that you don't need it anymore?

2021-08-06 07:27 UTC, vincenzocorso commented
I solved it another way for now 👍